# result_dir=configs/llama2-7b-w4a4
result_dir=configs/llama2-7b-w2a16


port=29504
GPU_NUM=1    # 该任务需要的GPU个数

THRESHOLD=0.05   # 当GPU内存利用率低于THRESHOLD，视为该GPU为空闲
WAIT_MODE=true   # true：循环等待GPU满足。 false：GPU不满足直接退出 
WAIT_INTERVAL=60 # 循环等待间隔，单位为秒，只在WAIT_MODE=true时起效。
